### PR TITLE
Add support for boolean eol response from Endoflife.date

### LINKED ISSUE #4: Support `eol` boolean response from endoflife.date
### Issue
endoflife.date can return either a datestring _or_ a boolean for the value in `eol` for a particular cycle. Support that response as well.

See the [Rails 7](https://endoflife.date/api/rails/7.0.json) response as an example.

### To reproduce
in the console:
```ruby
irb(main):001:0> EOL.info('ruby', cycle: '2.6').supported?
=> false
irb(main):002:0> EOL.info('rails', cycle: '7.0').supported?
lib/eol_rb/models/cycle.rb:11:in `parse': no implicit conversion of false into String (TypeError)

        @eol = Date.parse(specs.fetch("eol"))
                          ^^^^^^^^^^^^^^^^^^
	from lib/eol_rb/models/cycle.rb:11:in `initialize'
	from lib/eol_rb/cycle.rb:26:in `new'
	from lib/eol_rb/cycle.rb:26:in `get'
	from lib/eol_rb.rb:43:in `info'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/forwardable.rb:240:in `info'
	from (irb):2:in `<main>'
	from bin/console:20:in `<main>'
```

### PR DESCRIPTION
**Pull request by lomky**
Fixes #4 

See [commits fc3d5b0 and a4badeb in isolation](https://github.com/Coolomina/eol-rb/pull/6/files/da5964fe96c8c0ccd8554e24180c2d4afc8a6dae..a4badeb9ab839413370f0a6798462b8fbff713b0) for the proper diff for `cycle_spec.rb`

### CODE REVIEW

**Comment by lomky** [comment]
I believe these failures on `a4badeb` are from github's action issue, and will succeed on rerun.

**Comment by lomky** [comment]
@Coolomina is this addition welcome, and if so what do you think about doing a `0.6.0` gem release once it is merged in?

**Comment by DTrejo** [comment]
Thanks for your work on this @lomky and @Coolomina, this makes it easier to use the library 🙇🏻‍♂️ 🎉

**Comment by Coolomina** [comment]
Thanks for the good stuff @lomky . I'll check the failing checks at some point this week.

**Pull request merged**
